controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - slide_base_joint
      - body_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - roll_wrist_joint
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: stand_pose